export const PROJECT_MANAGER = "asst_bq9NG8R17bV4sQCr5QYNPDmy"
export const PROJECT_ARCHITECT = "asst_jftO66hPuDIj6I01oYrkBZ2Q"
export const FEATURE_ARCHITECT = "asst_ZReg0BdYMLJK46pmzU7e8FCq"
export const FEATURE_ARCHITECT_REVIEWER = "asst_yvVOTGypqNMbiizi2LXNOUHP"
export const DEVELOPER = "asst_NIavcQKJhDam0sZ6fImYn4Yp"
export const CODE_REVIEWER = "asst_32hh5N8OWbdPH1w2WT6eND2y"
